package org.spoutcraft.launcher.api;

public enum Event {
	BAD_LOGIN,
	FINISHED_UPDATE_CHECK,
	MINECRAFT_NETWORK_DOWN,
	RUN_GAME,
	SUCESSFUL_LOGIN,
	UPDATE_FINISHED,
	UPDATE_FAILED,
	USER_NOT_PREMIUM,
	VALIDATION_PASSED,
	VALIDATION_FAILED;
}
